/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CarteNfcRouteImport } from './routes/carte-nfc'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStyleRouteImport } from './routes/dashboard.style'
import { Route as DashboardShareRouteImport } from './routes/dashboard.share'
import { Route as DashboardCardRouteImport } from './routes/dashboard.card'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteNfcRoute = CarteNfcRouteImport.update({
  id: '/carte-nfc',
  path: '/carte-nfc',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStyleRoute = DashboardStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShareRoute = DashboardShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCardRoute = DashboardCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/carte-nfc': typeof CarteNfcRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/card': typeof DashboardCardRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/style': typeof DashboardStyleRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/carte-nfc': typeof CarteNfcRoute
  '/pricing': typeof PricingRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/card': typeof DashboardCardRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/style': typeof DashboardStyleRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/carte-nfc': typeof CarteNfcRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/card': typeof DashboardCardRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/style': typeof DashboardStyleRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/carte-nfc'
    | '/dashboard'
    | '/pricing'
    | '/dashboard/account'
    | '/dashboard/card'
    | '/dashboard/share'
    | '/dashboard/style'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/carte-nfc'
    | '/pricing'
    | '/dashboard/account'
    | '/dashboard/card'
    | '/dashboard/share'
    | '/dashboard/style'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/carte-nfc'
    | '/dashboard'
    | '/pricing'
    | '/dashboard/account'
    | '/dashboard/card'
    | '/dashboard/share'
    | '/dashboard/style'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  CarteNfcRoute: typeof CarteNfcRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte-nfc': {
      id: '/carte-nfc'
      path: '/carte-nfc'
      fullPath: '/carte-nfc'
      preLoaderRoute: typeof CarteNfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/style': {
      id: '/dashboard/style'
      path: '/style'
      fullPath: '/dashboard/style'
      preLoaderRoute: typeof DashboardStyleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/share': {
      id: '/dashboard/share'
      path: '/share'
      fullPath: '/dashboard/share'
      preLoaderRoute: typeof DashboardShareRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/card': {
      id: '/dashboard/card'
      path: '/card'
      fullPath: '/dashboard/card'
      preLoaderRoute: typeof DashboardCardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardCardRoute: typeof DashboardCardRoute
  DashboardShareRoute: typeof DashboardShareRoute
  DashboardStyleRoute: typeof DashboardStyleRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardCardRoute: DashboardCardRoute,
  DashboardShareRoute: DashboardShareRoute,
  DashboardStyleRoute: DashboardStyleRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  CarteNfcRoute: CarteNfcRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
